CREATE TABLE "activities" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"strava_id" bigint NOT NULL,
	"external_id" text,
	"upload_id" bigint,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"sport_type" text NOT NULL,
	"workout_type" integer,
	"start_date" timestamp with time zone NOT NULL,
	"start_date_local" timestamp NOT NULL,
	"timezone" text,
	"utc_offset" double precision,
	"distance" double precision,
	"total_elevation_gain" double precision,
	"elev_high" double precision,
	"elev_low" double precision,
	"moving_time" integer,
	"elapsed_time" integer,
	"average_speed" double precision,
	"max_speed" double precision,
	"average_watts" double precision,
	"weighted_average_watts" integer,
	"max_watts" integer,
	"kilojoules" double precision,
	"device_watts" boolean,
	"has_heartrate" boolean DEFAULT false,
	"average_heartrate" double precision,
	"max_heartrate" double precision,
	"average_cadence" double precision,
	"summary_polyline" text,
	"start_lat" double precision,
	"start_lng" double precision,
	"trainer" boolean DEFAULT false,
	"commute" boolean DEFAULT false,
	"manual" boolean DEFAULT false,
	"gear_id" text,
	"device_name" text,
	"suffer_score" integer,
	"pr_count" integer DEFAULT 0,
	"calories" double precision,
	"raw_data" jsonb NOT NULL,
	"detail_fetched" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "activities_strava_id_unique" UNIQUE("strava_id")
);
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "last_sync_at" timestamp;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activities_user_id_idx" ON "activities" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "activities_start_date_idx" ON "activities" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "activities_type_idx" ON "activities" USING btree ("type");